### PR TITLE
CI

### PR DESCRIPTION
**Pull request by kevincobain2000**

### CODE REVIEW

**Comment by juev** [comment]
Hello, why you included bin folder to repository??

Do you need a help?

**Comment by kevincobain2000** [comment]
To publish binary that can be installed via curl. Gotta need to upload binary somewhere :)

**Comment by juev** [comment]
You can use goreleaser for building and publish binary files to project artifacts.
For example:
https://github.com/juev/starred

All binary files you can view on Releases page.

**Comment by kevincobain2000** [comment]
Thanks, and yea I have heard about goreleaser and wanted to add that to the CI.

For following reasons I didn't do it

1. The Github Release, uploads a tar (as far as I know, I could be wrong I have only looked at it). 
And I wanted to reduce the number of dependencies, such as `tar` might not be installed on a system for a user. Therefore, I simply provide [direct binary file via curl.](https://github.com/kevincobain2000/gobrew/blob/master/git.io.sh#L48) 
In fact, insde the library `gobrew` it uses go to untar the source of go, instead of calling tar as a secondary os command.
2. Laziness :(

**Comment by juev** [comment]
You can configure goreleaser or just your build system for storing binary files on release page without tar. 😆

If you want it, I can configured it.

**Comment by kevincobain2000** [comment]
Thanks for the hand.
There'd be one more issue then
https://github.com/juev/starred/releases/download/0.0.5/starred_0.0.5_Darwin_arm64.tar.gz

In order to download, how can I download always the latest version without providing the tag version info.
Currently I am doing this as you already saw:

```
curl -kLs https://raw.githubusercontent.com/kevincobain2000/gobrew/master/bin/$GOBREW_ARCH_BIN -o $GOBREW_BIN_DIR/gobrew
```

I believe after the release, it'd have to provide a version number on that URL

**Comment by juev** [comment]
I create [new issue](https://github.com/kevincobain2000/gobrew/issues/34) for discuss this problem.

**Pull request merged**
