### PR TITLE
fix: fail script process on errors

### PR DESCRIPTION
**Pull request by juev**
Fixed: #205

### CODE REVIEW

**Comment by kevincobain2000** [comment]
Going to bed now. Night bud.

**Comment by juev** [comment]
Sweet dreams!

**Comment by AviDuda** [comment]
This change made action-gobrew fail with this:

```
Run kevincobain2000/action-gobrew@v2
Run echo "$HOME/.gobrew/current/bin" >> $GITHUB_PATH
sh: 3: set: Illegal option -o pipefail
Error: Process completed with exit code 2.
```

**Comment by scottames** [comment]
> This change made action-gobrew fail with this:
> 
> ```
> Run kevincobain2000/action-gobrew@v2
> Run echo "$HOME/.gobrew/current/bin" >> $GITHUB_PATH
> sh: 3: set: Illegal option -o pipefail
> Error: Process completed with exit code 2.
> ```

Running into this as well. Opened an issue over there: https://github.com/kevincobain2000/action-gobrew/issues/4. LMK if it should be here instead.

**Pull request merged**
