### PR TITLE
unable to obtain mod version

### PR DESCRIPTION
**Pull request by kevincobain2000**
```
╰─$ go run cmd/gobrew/main.go use mod                                                                                                                                                                      
==> [Info] Fetching remote versions

==> [Info] Downloading version: mod
==> [Info] Downloading from: https://go.dev/dl/gomod.darwin-arm64.tar.gz
==> [Info] Downloading to: /Users/pulkit.kathuria/.gobrew/downloads
==> [Info] Downloading version failed: https://go.dev/dl/gomod.darwin-arm64.tar.gz returned status code 404
==> [Error]: Please check connectivity to url: https://go.dev/dl/gomod.darwin-arm64.tar.gz
                                                                   ↑ Fixes
```

### CODE REVIEW

**Comment by kevincobain2000** [comment]
Sorry let me merge without review, our other CI has been failing.

**Comment by juev** [comment]
What test data can be used for verification?

On which repository did you conduct tests?

**Comment by kevincobain2000** [comment]
repo: actually testing right now
Screenshot 2023-11-12 at 20 30 36

**Comment by kevincobain2000** [comment]
Before and After Update

```sh
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/aketemite ‹master●›
╰─$ cat go.mod|grep go|head -1
go 1.21.4
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/aketemite ‹master●›
╰─$ gobrew use mod
==> [Info] Fetching remote versions

==> [Info] Downloading version: mod
==> [Info] Downloading from: https://go.dev/dl/gomod.darwin-arm64.tar.gz
==> [Info] Downloading to: /Users/pulkit.kathuria/.gobrew/downloads
==> [Info] Downloading version failed: https://go.dev/dl/gomod.darwin-arm64.tar.gz returned status code 404
==> [Error]: Please check connectivity to url: https://go.dev/dl/gomod.darwin-arm64.tar.gz
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/aketemite ‹master●›
╰─$ gobrew self-update                                                                                                                                                                                      1 ↵
Downloading 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (6.0/6.0 MB, 1.8 MB/s)
Upgrade successful
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/aketemite ‹master●›
╰─$ gobrew use mod
==> [Info] Version: 1.21.4 exists
==> [Info] Changing go version to: 1.21.4
==> [Success] Changed go version to: 1.21.4
╭─pulkit.kathuria@JP-GCJKVGQK0G^M ~/git/aketemite ‹master●›
╰─$ gobrew version
[INFO] gobrew version is 1.9.7
```

**Comment by juev** [comment]
Cool, thank you!

**Pull request merged**
