### PR TITLE
Tests 10122023

### LINKED ISSUE #127: Unit tests
We need unit tests in order to catch errors before release.

 1. It is necessary to prepare mocks for the http client and for working with the file system
 2. It is advisable to cover all used functions with tests.

I think that within the framework of this issue a PR will be created, which we will release only when ready.  We will discuss this separately.

### PR DESCRIPTION
**Pull request by juev**
- add config for GoBrew
- rewrite tests to use httptest

Resolve #127

### CODE REVIEW

**Comment by juev** [comment]
test time was improved :)

**Comment by juev** [comment]
I will check tests with windows

**Comment by juev** [comment]
On Windows we had a problem with tests.
The uploaded files were blocked by the main go process, which prevented the temporary directory from being cleaned up in a timely manner.  Because of this, certain special effects arose.
Why not waste time solving this problem while I disabled tests on Windows, as was the case before.

**Comment by juev** [comment]
Interesting question. Is it necessary to rewrite the history of the comedians to make the story cleaner? And did the changelog contain only the necessary information?

**Review by kevincobain2000 — APPROVED** [review]
woah

**Comment by juev** [comment]
In this MR I also changed the client to work with http.  I returned it back so as not to break the work via proxy.

**Comment by kevincobain2000** [comment]
> In this MR I also changed the client to work with http. I returned it back so as not to break the work via proxy.

Got it, thanks! No worries.

**Review by kevincobain2000 — APPROVED** [review]

**Comment by kevincobain2000** [comment]
Will push new tag at night

**Comment by kevincobain2000** [comment]
> In this MR I also changed the client to work with http. I returned it back so as not to break the work via proxy.

Pushed to `v1.10.5`

Tested behind proxy too, works as intended.

**Pull request merged**
